version: '2'

services:
    db:
        container_name: PostgreSQL
        image: postgres:latest
        ports:
        - "5432:5432"
        environment:
        - POSTGRES_PASSWORD = sonar
        - POSTGRES_USER = sonar
        - POSTGRES_DATABASE = sonar
        volumes:
        - /var/lib/postgresql:/var/lib/postgresql
        networks:
        - sonarnetwork

    SonarQube:
        container_name: SonarQube
        image: sonarqube:latest
        volumes:
        - /opt/db/sonarqube/:/var/lib/postgresql
        ports:
        - "9000:9000"
        - "443"
        environment:
        - SONARQUBE_JDBC_USERNAME = sonar
        - SONARQUBE_JDBC_PASSWORD = sonar
        - SONARQUBE_JDBC_URL = jdbc:postgresql://localhost/sonar
        links:
        - db
        networks:
        - sonarnetwork
networks:
    sonarnetwork: